CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(191) UNIQUE NOT NULL,
  pw_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(191) UNIQUE NOT NULL,
  title VARCHAR(191) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  tags VARCHAR(255) DEFAULT '',
  is_public TINYINT(1) DEFAULT 0,
  version INT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE note_terms (
  note_id INT NOT NULL,
  term VARCHAR(64) NOT NULL,
  tf FLOAT NOT NULL,
  PRIMARY KEY (note_id, term),
  FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE
);

CREATE TABLE note_links (
  src_id INT NOT NULL,
  dst_id INT NOT NULL,
  score FLOAT NOT NULL,
  PRIMARY KEY (src_id, dst_id),
  FOREIGN KEY (src_id) REFERENCES notes(id) ON DELETE CASCADE,
  FOREIGN KEY (dst_id) REFERENCES notes(id) ON DELETE CASCADE
);

ALTER TABLE notes ADD FULLTEXT ft_title_content (title, content);
